// ~60 popular freelance niches for the searchable picker in Settings.
export const POPULAR_NICHES: string[] = [
  // Development
  "Full-Stack Developer",
  "Frontend Developer",
  "Backend Developer",
  "React Developer",
  "Next.js Developer",
  "Mobile App Developer",
  "iOS Developer",
  "Android Developer",
  "WordPress Developer",
  "Shopify Developer",
  "Webflow Developer",
  "No-Code Developer",
  "Python Developer",
  "Node.js Developer",
  "DevOps Engineer",
  "Blockchain Developer",
  "Game Developer",
  "QA / Test Engineer",
  // Design
  "UI/UX Designer",
  "Product Designer",
  "Graphic Designer",
  "Brand Identity Designer",
  "Logo Designer",
  "Web Designer",
  "Illustrator",
  "Motion Graphics Designer",
  "3D Artist",
  "Presentation Designer",
  // Writing
  "Copywriter",
  "Content Writer",
  "Technical Writer",
  "SEO Writer",
  "Ghostwriter",
  "Scriptwriter",
  "Grant Writer",
  "Email Copywriter",
  // Marketing
  "Digital Marketer",
  "SEO Specialist",
  "Social Media Manager",
  "Paid Ads Specialist",
  "Email Marketing Specialist",
  "Growth Marketer",
  "Content Strategist",
  "Affiliate Marketer",
  // Video & Audio
  "Video Editor",
  "Videographer",
  "Animator",
  "Podcast Editor",
  "Audio Engineer",
  "Voice-Over Artist",
  "YouTube Specialist",
  // Business & Data
  "Virtual Assistant",
  "Project Manager",
  "Business Consultant",
  "Data Analyst",
  "Data Scientist",
  "Financial Analyst",
  "Bookkeeper",
  // AI & Emerging
  "AI Engineer",
  "Prompt Engineer",
  "Machine Learning Engineer",
  "Automation Specialist",
];
