/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StrategyRouteImport } from './routes/strategy'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SSlugRouteImport } from './routes/s.$slug'
import { Route as PSlugRouteImport } from './routes/p.$slug'
import { Route as CtSlugRouteImport } from './routes/ct.$slug'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedScoutRouteImport } from './routes/_authenticated/scout'
import { Route as AuthenticatedSavedRouteImport } from './routes/_authenticated/saved'
import { Route as AuthenticatedResearchRouteImport } from './routes/_authenticated/research'
import { Route as AuthenticatedPortfolioRouteImport } from './routes/_authenticated/portfolio'
import { Route as AuthenticatedNewRouteImport } from './routes/_authenticated/new'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedConversionRouteImport } from './routes/_authenticated/conversion'
import { Route as AuthenticatedContestRouteImport } from './routes/_authenticated/contest'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'

const StrategyRoute = StrategyRouteImport.update({
  id: '/strategy',
  path: '/strategy',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SSlugRoute = SSlugRouteImport.update({
  id: '/s/$slug',
  path: '/s/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CtSlugRoute = CtSlugRouteImport.update({
  id: '/ct/$slug',
  path: '/ct/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedScoutRoute = AuthenticatedScoutRouteImport.update({
  id: '/scout',
  path: '/scout',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSavedRoute = AuthenticatedSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedResearchRoute = AuthenticatedResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPortfolioRoute = AuthenticatedPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNewRoute = AuthenticatedNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConversionRoute = AuthenticatedConversionRouteImport.update({
  id: '/conversion',
  path: '/conversion',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedContestRoute = AuthenticatedContestRouteImport.update({
  id: '/contest',
  path: '/contest',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/strategy': typeof StrategyRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/contest': typeof AuthenticatedContestRoute
  '/conversion': typeof AuthenticatedConversionRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/new': typeof AuthenticatedNewRoute
  '/portfolio': typeof AuthenticatedPortfolioRoute
  '/research': typeof AuthenticatedResearchRoute
  '/saved': typeof AuthenticatedSavedRoute
  '/scout': typeof AuthenticatedScoutRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/ct/$slug': typeof CtSlugRoute
  '/p/$slug': typeof PSlugRoute
  '/s/$slug': typeof SSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/strategy': typeof StrategyRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/contest': typeof AuthenticatedContestRoute
  '/conversion': typeof AuthenticatedConversionRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/new': typeof AuthenticatedNewRoute
  '/portfolio': typeof AuthenticatedPortfolioRoute
  '/research': typeof AuthenticatedResearchRoute
  '/saved': typeof AuthenticatedSavedRoute
  '/scout': typeof AuthenticatedScoutRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/ct/$slug': typeof CtSlugRoute
  '/p/$slug': typeof PSlugRoute
  '/s/$slug': typeof SSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/strategy': typeof StrategyRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/contest': typeof AuthenticatedContestRoute
  '/_authenticated/conversion': typeof AuthenticatedConversionRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/new': typeof AuthenticatedNewRoute
  '/_authenticated/portfolio': typeof AuthenticatedPortfolioRoute
  '/_authenticated/research': typeof AuthenticatedResearchRoute
  '/_authenticated/saved': typeof AuthenticatedSavedRoute
  '/_authenticated/scout': typeof AuthenticatedScoutRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/ct/$slug': typeof CtSlugRoute
  '/p/$slug': typeof PSlugRoute
  '/s/$slug': typeof SSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/strategy'
    | '/admin'
    | '/contest'
    | '/conversion'
    | '/dashboard'
    | '/history'
    | '/new'
    | '/portfolio'
    | '/research'
    | '/saved'
    | '/scout'
    | '/settings'
    | '/ct/$slug'
    | '/p/$slug'
    | '/s/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/strategy'
    | '/admin'
    | '/contest'
    | '/conversion'
    | '/dashboard'
    | '/history'
    | '/new'
    | '/portfolio'
    | '/research'
    | '/saved'
    | '/scout'
    | '/settings'
    | '/ct/$slug'
    | '/p/$slug'
    | '/s/$slug'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/strategy'
    | '/_authenticated/admin'
    | '/_authenticated/contest'
    | '/_authenticated/conversion'
    | '/_authenticated/dashboard'
    | '/_authenticated/history'
    | '/_authenticated/new'
    | '/_authenticated/portfolio'
    | '/_authenticated/research'
    | '/_authenticated/saved'
    | '/_authenticated/scout'
    | '/_authenticated/settings'
    | '/ct/$slug'
    | '/p/$slug'
    | '/s/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  StrategyRoute: typeof StrategyRoute
  CtSlugRoute: typeof CtSlugRoute
  PSlugRoute: typeof PSlugRoute
  SSlugRoute: typeof SSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/strategy': {
      id: '/strategy'
      path: '/strategy'
      fullPath: '/strategy'
      preLoaderRoute: typeof StrategyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$slug': {
      id: '/s/$slug'
      path: '/s/$slug'
      fullPath: '/s/$slug'
      preLoaderRoute: typeof SSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ct/$slug': {
      id: '/ct/$slug'
      path: '/ct/$slug'
      fullPath: '/ct/$slug'
      preLoaderRoute: typeof CtSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/scout': {
      id: '/_authenticated/scout'
      path: '/scout'
      fullPath: '/scout'
      preLoaderRoute: typeof AuthenticatedScoutRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/saved': {
      id: '/_authenticated/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof AuthenticatedSavedRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/research': {
      id: '/_authenticated/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof AuthenticatedResearchRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/portfolio': {
      id: '/_authenticated/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof AuthenticatedPortfolioRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/new': {
      id: '/_authenticated/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof AuthenticatedNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/conversion': {
      id: '/_authenticated/conversion'
      path: '/conversion'
      fullPath: '/conversion'
      preLoaderRoute: typeof AuthenticatedConversionRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/contest': {
      id: '/_authenticated/contest'
      path: '/contest'
      fullPath: '/contest'
      preLoaderRoute: typeof AuthenticatedContestRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedContestRoute: typeof AuthenticatedContestRoute
  AuthenticatedConversionRoute: typeof AuthenticatedConversionRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedNewRoute: typeof AuthenticatedNewRoute
  AuthenticatedPortfolioRoute: typeof AuthenticatedPortfolioRoute
  AuthenticatedResearchRoute: typeof AuthenticatedResearchRoute
  AuthenticatedSavedRoute: typeof AuthenticatedSavedRoute
  AuthenticatedScoutRoute: typeof AuthenticatedScoutRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedContestRoute: AuthenticatedContestRoute,
  AuthenticatedConversionRoute: AuthenticatedConversionRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedNewRoute: AuthenticatedNewRoute,
  AuthenticatedPortfolioRoute: AuthenticatedPortfolioRoute,
  AuthenticatedResearchRoute: AuthenticatedResearchRoute,
  AuthenticatedSavedRoute: AuthenticatedSavedRoute,
  AuthenticatedScoutRoute: AuthenticatedScoutRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  StrategyRoute: StrategyRoute,
  CtSlugRoute: CtSlugRoute,
  PSlugRoute: PSlugRoute,
  SSlugRoute: SSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
